version: '3'

services:
  db:
    image: postgres:9.6.5
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/video_library
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
      - db:db

volumes:
  postgres_data: